language: node_js

node_js:
  - 12

env: 
  - 'DATABASE_URL=postgresql://postgres@localhost:5432/multi_fruit_basket'

before_script:
  - npm install
  - psql -c 'create database  multi_fruit_basket;' -U postgres
  - psql -U postgres -d multi_fruit_basket -a -f database.sql

services:
  - postgresql
addons:
  postgresql: '9.4'
  apt:
    packages:
      - postgresql-server-dev-9.4